[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.22'
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "https://eth-sepolia.api.onfinality.io/public"
base = "https://base.llamarpc.com"